spring.application.name=API-Property-Management

# Database
spring.datasource.url=${DB_URL}/Properties
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Security Key
api.security.token.secret=${JWT_SECRET_KEY}

spring.flyway.clean-on-validation-error=true
spring.flyway.validate-on-migrate=false